version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
      
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
    - "5000:5000"
    
volumes:
  portainer_data:
