version: "3"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/data
  gitea:
    build: gitea
    image: dmundt/gitea
    container_name: gitea
    environment:
      - RUN_MODE=prod
      - SSH_DOMAIN=titan:12022
      - SSH_PORT=12022
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "12022:22"
  # backup:
  #   build: volume-backup
  #   image: dmundt/volume-backup
  #   container_name: backup
      
  # registry-ui:
  #   image: joxit/docker-registry-ui
  #   container_name: registry-ui
  #   restart: always
  #   ports:
  #   - "80:80"
  #   environment:
  #    - URL=http://127.0.0.1:5000
  #    - DELETE_IMAGES=true
  #    - REGISTRY_TITLE="DockPi registry"

volumes:
  gitea_data:
  portainer_data:
  registry_data:

networks:
  gitea:
    external: false
