version: "3"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
  gitea:
    build: gitea
    image: dmundt/gitea:1.7.4
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - gitea_data:/data
    ports:
      - "3000:3000"
      - "222:22"
      
  # registry-ui:
  #   image: joxit/docker-registry-ui
  #   container_name: registry-ui
  #   restart: always
  #   ports:
  #   - "80:80"
  #   environment:
  #    - URL=http://127.0.0.1:5000
  #    - DELETE_IMAGES=true
  #    - REGISTRY_TITLE="DockPi registry"

volumes:
  portainer_data:
  gitea_data:

networks:
  gitea:
    external: false
